# Generated by Django 5.2.7 on 2025-10-20 12:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=20, unique=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Data Pelanggan',
                'verbose_name_plural': 'Data Pelanggan',
            },
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_periksa', models.DateField(default=django.utils.timezone.now)),
                ('od_sph', models.CharField(default='Plano', max_length=10, verbose_name='SPH (Kanan)')),
                ('od_cyl', models.CharField(default='-', max_length=10, verbose_name='CYL (Kanan)')),
                ('od_axis', models.CharField(default='-', max_length=10, verbose_name='AXIS (Kanan)')),
                ('od_add', models.CharField(default='-', max_length=10, verbose_name='ADD (Kanan)')),
                ('os_sph', models.CharField(default='Plano', max_length=10, verbose_name='SPH (Kiri)')),
                ('os_cyl', models.CharField(default='-', max_length=10, verbose_name='CYL (Kiri)')),
                ('os_axis', models.CharField(default='-', max_length=10, verbose_name='AXIS (Kiri)')),
                ('os_add', models.CharField(default='-', max_length=10, verbose_name='ADD (Kiri)')),
                ('pd', models.CharField(blank=True, max_length=10, null=True, verbose_name='PD (Pupil Distance)')),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resep_history', to='pasien.pelanggan')),
            ],
            options={
                'verbose_name': 'Data Resep',
                'verbose_name_plural': 'Data Resep',
                'ordering': ['-tanggal_periksa'],
            },
        ),
    ]
