# Generated by Django 5.2.7 on 2025-10-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resep',
            name='indeks_lensa',
            field=models.CharField(choices=[('1.56', '1.56'), ('1.60', '1.60'), ('1.67', '1.67'), ('1.74', '1.74'), ('LAIN', 'Lainnya (misal: 1.50, 1.59)')], default='1.56', max_length=5, verbose_name='Indeks Lensa'),
        ),
        migrations.AddField(
            model_name='resep',
            name='jenis_coating',
            field=models.CharField(choices=[('CRMC', 'CRMC (Standard)'), ('BLR', 'Blueray'), ('PHC', 'Photochromic'), ('BLC', 'Bluechromic (Blueray + Photochromic)'), ('LAIN', 'Lainnya')], default='CRMC', max_length=5, verbose_name='Jenis Coating/Bahan'),
        ),
        migrations.AddField(
            model_name='resep',
            name='jenis_lensa',
            field=models.CharField(choices=[('SV', 'Single Vision'), ('BF', 'Bifokal'), ('PG', 'Progresif'), ('OFF', 'Office / Baca'), ('LAIN', 'Lainnya')], default='SV', max_length=5, verbose_name='Jenis Lensa'),
        ),
    ]
