# Generated by Django 5.2.7 on 2025-10-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0002_resep_indeks_lensa_resep_jenis_coating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resep',
            name='diskon',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='resep',
            name='harga_frame',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='resep',
            name='harga_lensa',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='resep',
            name='lunas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='total_bayar',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
