# Generated by Django 5.2.7 on 2025-10-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0003_resep_diskon_resep_harga_frame_resep_harga_lensa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resep',
            name='total_bayar',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10, verbose_name='Total Bayar (Rp)'),
        ),
    ]
